app/ideer/models.py
from sqlalchemy.orm import relationship, backref
from app import db


association_table = db.Table('categories',
    db.Column('category_id', db.Integer, db.ForeignKey('ideer_category.id')),
    db.Column('idea_id', db.Integer, db.ForeignKey('ideer_idea.id'))
)

class Category(db.Model):
    __tablename__ = 'ideer_category'
    id = db.Column(db.Integer, primary_key=True)
    #parent_id = db.ForeignKey(id)
    parent_id = db.Column(db.Integer, db.ForeignKey('ideer_category.id'))
    sub_categories = relationship('Category', remote_side=[id])
    title = db.Column(db.String(50))
    
    def __init__(self, title, parent=None):
        self.parent_id = parent
        self.title = title

    def __unicode__(self):
        return self.title


class Idea(db.Model):
    __tablename__ = 'ideer_idea'
    id = db.Column(db.Integer, primary_key=True)
    categories = relationship('Category', backref='ideas', secondary=association_table)
    text = db.Column(db.String(255))
    
    #def __init__(self, text, category):
    #    self.text = text
    #    self.categories.add(category)

    def __unicode__(self):
        return self.text[:15]

app/users/models.py
from app import db
from app.users import constants as USER


class User(db.Model):

      __tablename__ = 'users_user'
      id = db.Column(db.Integer, primary_key=True)
      name = db.Column(db.String(50), unique=True)
      email = db.Column(db.String(120), unique=True)
      password = db.Column(db.String(120))
      role = db.Column(db.SmallInteger, default=USER.USER)
      status = db.Column(db.SmallInteger, default=USER.NEW)

      def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

      def getStatus(self):
        return USER.STATUS[self.status]

      def getRole(self):
        return USER.ROLE[self.role]

      def __repr__(self):
          return '<User %r>' % (self.name)

app/ideer/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField
from wtforms.validators import Required


class IdeaForm(Form):
    idea = TextAreaField('idea', [Required()])
    category = TextField('category', [Required()])

app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email

class LoginForm(Form):
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])

class RegisterForm(Form):
    name = TextField('NickName', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField('Repeat Password', [
        Required(),
        EqualTo('password', message='Passwords must match')
        ])
    accept_tos = BooleanField('I accept the TOS', [Required()])
    recaptcha = RecaptchaField()

app/__init__.py
from flask import Flask, render_template
from flask.ext.sqlalchemy import SQLAlchemy
app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.users.views import mod as usersModule
from app.ideer.views import mod as ideerModule
from app.home.views import mod as homeModule
app.register_blueprint(usersModule)
app.register_blueprint(ideerModule)
app.register_blueprint(homeModule)

# Later on you'll import the other blueprints the same way:
#from app.comments.views import mod as commentsModule
#from app.posts.views import mod as postsModule
#app.register_blueprint(commentsModule)
#app.register_blueprint(postsModule)

app/home/views.py
from flask import Blueprint, render_template

mod = Blueprint('home', __name__, url_prefix='/')

@mod.route('/')
def home():
    return render_template('home/home.html')

app/ideer/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from app import db
from app.ideer.models import Category, Idea
from app.ideer.forms import IdeaForm


mod = Blueprint('ideer', __name__, url_prefix='/ideer')


@mod.route('/')
def home():
    return "Home Page"


@mod.route('/create-idea', methods=['GET', 'POST'])
def create_idea():
    form = IdeaForm()
    if form.validate_on_submit():
        #get categories
        categories = form.category.data.split(',')
        idea_categories = []
        for category in categories:
            c = Category.query.filter_by(title=category).first()
            if c:
                idea_categories.append(c)
            else:
                #since category doesn't exist create it
                c = Category(title=category)
                db.session.add(c)
                #TODO: remove commit
                db.session.commit()
                idea_categories.append(c)
        new_idea = Idea(text=form.idea.data)
        new_idea.categories = idea_categories

        db.session.add(new_idea)
        db.session.commit()

        #redirect to the category of the new idea
        #TODO: multiple categories
        #TODO: go to idea?
        return redirect(url_for('ideer.home'))
    return render_template('ideer/create_idea.html', form=form)


#TODO: use slugs
@mod.route('/category/<id>')
def view_category(id):
    category = Category.query.get(id)
    ideas = category.ideas
    #TODO: button to copy idea to clipboard
    return render_template('ideer/category.html', category=category, ideas=ideas)

#TODO: search (startswith) for categories


@mod.route('/category')
def list_categories():
    # find categories without a parent
    categories = Category.query.all()
    #TODO: do this in one query
    #TODO: how to change dom element when it is selected
    #TODO: how to save it
    #Category.query.join(ContainerClass).filter(ContainerClass.id == 5).all()
    return render_template('ideer/list_categories.html', categories=categories)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/me/')
@requires_login
def home():
    return render_template("users/profile.html", user=g.user)

@mod.before_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            session['user_id'] = user.id
            flash('Welcome %s' % user.name)
            return redirect(url_for('users.home'))
        flash('Wrong email or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        user = User(name=form.name.data, email=form.email.data, \
            password=generate_password_hash(form.password.data))
        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()

        # Log the user in, as he now has an id
        session['user_id'] = user.id

        # flash will display a message to the user
        flash('Thanks for registering')
        # redirect user to the 'home' method of the user module.
        return redirect(url_for('users.home'))
    return render_template("users/register.html", form=form)

app/templates/base.html
<html>
    <head>
      <title>{% block title %}My Site{% endblock %}</title>
      {% block stylesheets %}
      <link rel="stylesheet" href="/static/css/reset-min.css" />
      <link rel="stylesheet" href="/static/css/main.css" />
      {% endblock stylesheets %}
      {% block javascript %}
      <script src="/static/js/main.js" type="text/javascript"></script>
      {% endblock javascript %}
    </head>
    <body>
      <div id="header">{% block header %}{% endblock %}</div>
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
            <p class="message flash-{{ category }}">{{ msg }}</p>
          {% endfor %}
        </div>
      </div>
      <div id="content">{% block content %}{% endblock content %}</div>
      <div id="footer">{% block footer %}{% endblock footer %}</div>
    </body>
</html>

app/templates/forms/macros.html
{% macro render_field(field) %}
      <div class="form_field">
      {{ field.label(class="label") }}
      {% if field.errors %}
          {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
          {{ field(class=css_class, **kwargs) }}
          <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
      {% else %}
          {{ field(**kwargs) }}
      {% endif %}
      </div>
{% endmacro %}

app/templates/home/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home Page</h1>
{% endblock %} 

app/templates/ideer/category.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ category }}</h1>

    {% for idea in ideas %}
        <p>{{ idea }}</p>
    {% endfor %}
{% endblock %}

app/templates/ideer/create_idea.html
{% extends "base.html" %}

{% block content %}
    <h1>Add new Idea</h1>

    {% from "forms/macros.html" import render_field %}
    <form method="POST" class="form">
      {{ form.csrf_token }}
      {{ render_field(form.idea, class="input textbox") }}
      {{ render_field(form.category, class="input text") }}
      <input type="submit" value="Add" class="button green">
    </form>
    <p><a href="{{ url_for('users.login') }}">Login</a></p>
{% endblock %}

app/templates/ideer/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home Page</h1>
{% endblock %}

app/templates/ideer/list_categories.html
{% extends "base.html" %}

{% block stylesheets %}
    {{ super() }}
    <link type=text/css href="{{ url_for('static', filename='css/jquery.min.css') }}">
    <style>
        #sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
        #sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
        #sortable li span { position: absolute; margin-left: -1.3em; }
    </style>
{% endblock stylesheets %}

{% block javascript %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/jquery-ui.min.js') }}" type="text/javascript"></script>
    <script>
        $(function() {
            $( "#sortable" ).sortable({
                items: 'li'
            });
            $( "#sortable" ).disableSelection();
            $( "#sortable" ).sortable({
                stop: function( ) {
                    // Cases category in a category
                    // Idea in a category
                    // Check if parent is a category
                    $( this ).addClass("ui-state-highlight");
                    var parentTag = $( this ).parent().get( 0 ).tagName;
                    $( this ).prepend( document.createTextNode( parentTag + " > " ) );
                }
            });
        });
    </script>
{% endblock javascript %}

{% block content %}
    <h1>Categories</h1>

    <ul id="sortable">
    {% for category in categories recursive %}
        <li name="category" class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>{{ category }}
            <ul>
            {% for idea in category.ideas %}
                <li name="idea">{{ idea }}</li>
            {% endfor %}
            </ul>
            {% if category.sub_categories %}
                {# <id="sortable">{{ loop(category.subcategories) }}</ul> #}
                {{ loop(category.subcategories) }}
            {%endif%}
        </li>
    {%endfor%}
    </ul>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      <input type="submit" value="Login" class="button green">
    </form>
    <a href="{{ url_for('users.register') }}">Register</a>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
   Hi {{ user.name }}!
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}

{% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, class="input text") }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      {{ render_field(form.confirm, class="input text") }}
      {{ render_field(form.accept_tos, class="input checkbox") }}
      <label>ReCaptcha</label>
      {{ form.recaptcha }}
      <input type="submit" value="Register" class="button green">
    </form>
    <a href="{{ url_for('users.login') }}">Login</a>
{% endblock %}